### ISSUE TITLE
Attribute Error when calling docker-compose -f run.sh up

### ISSUE THREAD

**Issue by lspitaels** [burke-software/schooldriver#226]
Hi,

I'm new user of DjangoSIS and I have a problem I call "docker-compose -f run.sh up". Do I need to do something particular?
Here the error: 
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 64, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 83, in get_project
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.config", line 68, in load
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.config", line 74, in from_dictionary
AttributeError: 'str' object has no attribute 'items'

Cheers,
Laurent

**Comment by bufke** [comment]
Same happens here. Try just `docker-compose up`.

May I ask what you're doing with this project? As you may have noticed it's not very active. Regrettably we don't have any major backers at this time and I'm working on other projects. Feel free to reach out directly to david at burkesoftware dot com

**Comment by lspitaels** [comment]
Thank you for your answer. I installed 'fig' and it works.
I'm using your project to computerize a our student data because there are still working on papers or on several old software. Now I'm still waiting the authorization of the direction to use it and replace the old system.

**Comment by dteklavya** [comment]
Hi David,

I'm trying to use it as well and I ran -

docker-compose run --rm web python manage.py migrate

and it pulls postgres and creates DB but fails to pull redis and throws the following error -

postgres:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.

Digest: sha256:66ba100bc635be1746daadd3ecfa46b51fbb767cd9fbc170edbf33483010065b
Status: Downloaded newer image for postgres:latest
Creating schooldriver_db_1...
Pulling redis (dockerfile/redis:latest)...
Pulling repository dockerfile/redis
Error: image dockerfile/redis:latest not found


However, I updated docker-compose.yml to 'image: redis' instead of 'image: dockerfile/redis' and it seems to be working.

Is this issue related or do I need to create a new one? Thanks.
